baseURL = "http://golang.design/go-questions"
languageCode = "zh-CN"
title = "Go 程序员面试笔试宝典"
theme = "book"

[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4
[markup.goldmark.renderer]
    unsafe= true
